### ISSUE TITLE
download with openload

### ISSUE THREAD

**Issue by ghost** [qgustavor/direct-mega#10]
hey.
i want to ask if there is a way to download the file direct to openload / my server..
they gave me error (in my server its
```
root@ubuntu:~# wget https://directme.ga/?!IOUHU!KEYKEYKEYKEYKEYKEYKEYKEY
-bash: !IOUHU!KEYKEYKEYKEYKEYKEYKEYKEY: event not found
```
)
-thanks!

**Comment by qgustavor** [comment]
The website use Service Workers, so everything works in client side. You can try using [megajs-cli](https://github.com/qgustavor/megajs-cli), most of the code is the same.

**Comment by qgustavor** [comment]
I'm closing this issue. If you found megajs-cli hard to install subscribe to [this issue](https://github.com/qgustavor/megajs-cli/issues/5).
