### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by qgustavor** [qgustavor/direct-mega#15]
For some reason some users are getting this error: "Unexpected end of JSON input"

I couldn't reproduce this error and for some reason the stack trace is empty. Does someone knows how to solve this bug?

**Comment by lms7** [comment]
Can I use this?

**Comment by qgustavor** [comment]
@lms7 Can you use what? You can use this website without problems. This issue is about people which is getting "Unexpected end of JSON input" errors. Are you getting this issue? Do you know how to fix this issue?

**Comment by qgustavor** [comment]
Fixed in last commit.
