### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by lms7** [qgustavor/direct-mega#16]
Please tell me how to use this in my website & send the files to an FTP Server or my own server, you know like Mega-Debrid

**Comment by qgustavor** [comment]
https://github.com/qgustavor/direct-mega#how-to-use

> When downloading a file replace `https://mega.nz` with `https://directme.ga`. **Everything works in your computer** and you can download anything **directly from MEGA**.

> You can view files, if your browser supports then, by using `view` before the `#` part. Folders are also supported: a link to a folder will show a list the files inside it so you can download or view one of those.

No, it's not like Mega-Debrid: as I emphasized above it works in your computer, no data is send to other servers. You download it directly from MEGA: this website just contacts the MEGA API, decrypts the result and downloads the result.

This website is hosted in GitHub Pages, so if you want to host a clone [download the source code](https://github.com/qgustavor/direct-mega/archive/master.zip), edit it as you wish, build the source (install Node, run `npm install` then `npm run build`) and host the `dist` folder in the root directory (or edit the source code to make it work in other directory) of any **HTTPS** server (it don't works over HTTP, even if you edit the source-code, as browsers only allow simulating downloads over HTTPS).

Service Worker is a new feature which allow many things, but one of the main features is allowing websites use JavaScript to control connections. So websites can fake downloads without requiring other server to download, decrypt and host files like the website you cited.

Please, **read the readme** before asking more questions... seems it's the third or fourth time someone asked me this question. 😑
