### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by qgustavor** [qgustavor/direct-mega#17]
Today Rollbar reported a bug from a Edge browser. Seems Edge 17 and Safari 11.1 now supports [Service Workers](https://caniuse.com/#feat=serviceworkers) and [Streams](https://caniuse.com/#feat=streams).

The bug reported was something like `resolve isn't a function` in [this line](https://github.com/qgustavor/direct-mega/blob/3817ef62b0585a560cc6f9c40a8149aebaee8f29/src/sw.js#L165). Anyone which can check the source code will notice that `resolve` is a function because it's how `new Promise` works. Either Edge's Promise implementation is buggy or their JavaScript engine is mistaking `resolve` (which was minified to `e`) with other variable (`event`, which was also minified to `e`, but in other scope), or other bug is happening.

There's someone which can test and debug the website in those browsers? I don't any computer which can run any of those browsers.

**Edit:** for some reason this kind of error is being too common, so I think I will need to detect Edge and block it from installing the Service Worker. I don't want to use user-agent detection, but it's a *edge* case which I think I can't detect using feature detection.

**Comment by qgustavor** [comment]
Disabled Service Workers on Microsoft Edge on commit 318d7f6d70d8d5fc2dccec29b2ec49654739db34

Instead of using user-agent detection it's creating a ReadableStream then trying to read it. On Chrome it works, on Edge it fails. When Microsoft fix this bug Edge will use Service Workers.

Can someone open an issue on Edge issue tracker relating this problem?

**Comment by qgustavor** [comment]
iOS Safari 11.3 supports service workers and streams. It returned this error:

```
json@[native code]
https://directme.ga/sw.js:2:9679
promiseReactionJob@[native code]
```

Seems it's a JSON parsing error (from a `Response.prototype.json`). Why MEGA is returning invalid JSON?

*Edit:* Mac OS Safari also returns this error.

**Comment by M47H3W** [comment]
Hello, I was wondering if this issue is known with Safari 11.1?

When I visit [https://directme.ga/?!MAsFwa4b!d8o1uz6SffMAATSQmERLIYITkyc-eTbKQ6xqI3IQSms](https://directme.ga/?!MAsFwa4b!d8o1uz6SffMAATSQmERLIYITkyc-eTbKQ6xqI3IQSms) on Safari 11.1, it will get stuck at `Please wait...` and will download an HTML file named directme.ga.html and will contain the following:


```
<!doctype html><html lang=en><meta charset=utf-8><title>Direct MEGA</title>
<meta name=viewport content="width=device-width,initial-scale=1">
<meta content=yes name=mobile-web-app-capable><style>body{margin:20px;line-height:1.6;font-size:18px;color:#444;padding:0 10px}h1,h2,h3{line-height:1.2}</style><body><noscript>Both MEGA and this page requires JavaScript enabled</noscript><script src="main.js"></script>
```

**Comment by qgustavor** [comment]
It's the first time I see this happening. Strange, my guess is that the
service worker triggers a download but the code which handles downloads on
Safari don't "know" the existence of service workers and try to download by
itself ignoring the response created by the service worker.
As I can't detect that the only solution I have is blacklisting the
versions of Safari which have this bug. Do you know what versions ate
affected?

**Comment by M47H3W** [comment]
From what I can tell it is on the latest Safari 11.1 only. I had tested with previous versions of Safari a couple months back and it worked fine.

**Comment by M47H3W** [comment]
Also, would you know where I could insert the proper if statements so that Safari doesn't utilize the service workers and instead go back to blobs?

**Comment by qgustavor** [comment]
It checks compatibility before installing. IIRC it's in main.js. For now it
only checks for service workers and if a readable stream can be created.
There isn't any code which uninstalls the worker on incompatible browsers.
You can add one in the worker.

**Comment by qgustavor** [comment]
@M47H3W Can you make a pull request fixing Safari 11.1 issue?

**Comment by M47H3W** [comment]
@qgustavor Sure, I think I got it working, but it's just a simple useragent check that uses fallback.js if Safari is detected. I'll try to publish a pull request asap.

**Comment by qgustavor** [comment]
Chrome have the same issue then resuming interrupted downloads: it ignores the service worker and downloads the index.html page.

Using `navigator.userAgent.includes('Version/11.1 Safari')` to detect Safari 11.1 is ok?

**Comment by qgustavor** [comment]
I updated the website with this check on dcacd62. Is it working now?

**Comment by M47H3W** [comment]
@qgustavor Yes, your code appears to be working now. 

I was able to fix it a few days ago by using a cheap method in main.js, it's almost identical to the same thing you did with the useragent check. I basically made it to automatically go to the `fallback() `function if Safari 11.1 is detected.

Also, when I began testing for a fix, it would still use service workers until I cleared my cache. So if anybody still cannot get it to work, clear your cache first.

This was what I came up with a few days ago:


> (function () {
>   var header = document.createElement('h1')
>   header.textContent = 'Direct MEGA'
>   document.body.appendChild(header)
> 
>   var installingMessage = document.createElement('p')
>   installingMessage.textContent = 'Please wait...'
>   window.installingMessage = installingMessage
>   document.body.appendChild(installingMessage)
> 
>   var location = window.location
>   var identifier = (location.hash.length > 2 ? location.hash : location.search || '').substr(1)
>   var hasFile = identifier.startsWith('!') || identifier.startsWith('F!')
>   **var useragent = navigator.userAgent**
>   var compatible = typeof ReadableStream === 'function'
>   if (compatible) {
>     try {
>       ;(new window.ReadableStream()).getReader().read()
>     } catch (e) {
>       compatible = false
>     }
>   }
> 
>   **if (useragent.includes("Version/11.1 Safari")){
>   	 fallback()
>   } else** if (navigator.serviceWorker && compatible) {
>     navigator.serviceWorker.register('sw.js', {scope: '.'})
>     .then(navigator.serviceWorker.ready)
>     .then(function () {
>       if (hasFile) {
>         location.href = location.pathname + '?' + identifier
>         console.log("We have SW")
>       } else {
>         location.href = 'https://github.com/qgustavor/direct-mega#direct-mega'
>       }
>     }, fallback)
>   } else if (hasFile) {
>     fallback()
>   } else {
>     location.href = 'https://github.com/qgustavor/direct-mega#direct-mega'
>   }
>   function fallback () {
>     console.log("We will fallback.")
>     var script = document.createElement('script')
>     script.src = 'fallback.js'
>     document.head.appendChild(script)
>   }
> }())

**Comment by qgustavor** [comment]
Seems it's the same logic [as here](https://github.com/qgustavor/direct-mega/commit/dcacd6237643811f18b4c583270c43677de0d395#diff-2770833218bd08d0b5d0c0157cfef742R19) but I put that check in the `compatible` variable so I don't need to add other `if` clause, also because simply calling `fallback()` will cause the fallback script to load even if there's no file to load.

I will close this issue.
